# ─── Stage 1: Build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache openssl libc6-compat
RUN npm install -g pnpm@latest

COPY package.json pnpm-workspace.yaml ./
COPY instances ./instances
COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend
RUN pnpm install --frozen-lockfile=false
RUN npx prisma generate
RUN pnpm build

# ─── Stage 2: Runner ──────────────────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

RUN apk add --no-cache openssl libc6-compat
RUN npm install -g pnpm@latest

COPY package.json pnpm-workspace.yaml ./
COPY instances ./instances
COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend
RUN pnpm install --prod --frozen-lockfile=false
RUN npx prisma generate
COPY --from=builder /app/apps/backend/dist ./dist

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push --skip-generate && node dist/src/main.js"]
