// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by prepare-instance.ps1 for instance: christian_tube

import 'base_feed_engine.dart';
import '../../features/engines/scripture/scripture_engine.dart';

const bool kMicroFeedEnabled = true;

BaseFeedEngine createActiveFeedEngine() => ScriptureEngine();