// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by prepare-instance.ps1 for instance: christian_tube

import '../../features/engines/scripture/scripture_engine.dart';

const bool kMicroFeedEnabled = true;

ScriptureEngine createActiveFeedEngine() => ScriptureEngine();