#!/usr/bin/env python3
"""
transcriber-worker.py — Long-running transcription + AI insights service.

Polls the PrivateTube PostgreSQL database for videos whose
`transcriptionStatus` is `pending`/`processing`, downloads the audio with
yt-dlp, transcribes it locally with faster-whisper (large-v3-turbo, int8 CPU),
writes back the transcript into the `Video.content` column, and then publishes
two assets to the instance's GitHub releases repository (default
`christian_tube` -> `rozariopersonal/Christian-Tube-Releases`):

    transcripts/<videoId>.md     full timestamped transcript
    insights/<videoId>.json      LLM extraction (bible quotes, ideas, truths)
    index.json                   repo manifest

Insights are generated by a local LLM served by Ollama (Qwen2.5 7B Instruct by
default) so no transcript content ever leaves the machine.

Resume behaviour: pending videos are polled. On startup any stale
`processing` rows (from a previously interrupted run) are swept back to
`pending`, so interrupted work still resumes; `completed`/`failed` are skipped
unless `--redo`/`--retry-failed` opt in. One-off runs (`--video-id`,
`--insights-resume`) mark their row `processing`, which the poller ignores, so
manual runs never race the polling loop.

Exit codes: 0 on clean shutdown, 2 no eligible videos in the initial pass.
"""
from __future__ import annotations

import argparse
import base64
import logging
import os
import signal
import subprocess
import sys
import tempfile
import time
import urllib.parse
import wave
from dataclasses import dataclass
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("transcriber-worker")

_split_to_epoch: float | None = None


@dataclass
class Config:
    database_url: str
    github_repo: str
    github_token: str
    llm_url: str
    llm_model: str
    llm_context: int
    work_dir: Path
    poll_interval: int
    batch_limit: int
    max_retries: int
    whisper_url: str | None = None
    whisper_model: str = "large-v3-turbo"
    whisper_model_dir: Path = Path("/opt/models")
    whisper_device: str = "cpu"
    whisper_compute: str = "int8"
    llm_timeout: int = 1800
    redo: bool = False
    retry_failed: bool = False
    once: bool = False
    no_llm: bool = False
    insights_resume: bool = False
    video_id: str | None = None


def load_config(args: argparse.Namespace) -> Config:
    def _env(name: str, default: str = "") -> str:
        return os.environ.get(name, default)

    db_url = _env("DATABASE_URL")
    token = _env("GITHUB_TOKEN")
    if not db_url:
        log.error("DATABASE_URL is required but was not provided.")
        raise SystemExit(1)
    if not token:
        log.error("GITHUB_TOKEN is required (fine-grained PAT with Contents: read/write on %s).",
                  _env("GITHUB_REPO", "rozariopersonal/Christian-Tube-Releases"))
        raise SystemExit(1)
    return Config(
        database_url=db_url,
        github_repo=_env("GITHUB_REPO", "rozariopersonal/Christian-Tube-Releases"),
        github_token=token,
        llm_url=_env("LLM_URL", "http://llm:11434").rstrip("/"),
        llm_model=_env("LLM_MODEL", "qwen2.5:7b"),
        llm_context=int(_env("LLM_CONTEXT", "32768")),
        llm_timeout=int(_env("LLM_TIMEOUT", "1800")),
        whisper_url=(_env("WHISPER_URL") or None),
        whisper_model=_env("WHISPER_MODEL", "large-v3-turbo"),
        whisper_model_dir=Path(_env("WHISPER_MODEL_DIR", "/opt/models")),
        whisper_device=_env("WHISPER_DEVICE", "cpu"),
        whisper_compute=_env("WHISPER_COMPUTE", "int8"),
        work_dir=Path(_env("WORK_DIR", "/work")),
        poll_interval=int(_env("POLL_INTERVAL", "300")),
        batch_limit=int(_env("BATCH_LIMIT", "5")),
        max_retries=int(_env("MAX_RETRIES", "3")),
        redo=args.redo,
        retry_failed=args.retry_failed,
        once=args.once,
        no_llm=args.no_llm,
        insights_resume=args.insights_resume,
        video_id=args.video_id or None,
    )


# --------------------------------------------------------------------------- #
# Database (libpq-safe URL handling mirrors scripts/transcribe.py)
# --------------------------------------------------------------------------- #
LIBPQ_PARAMS = {
    "host", "port", "dbname", "user", "password", "sslmode", "sslcert",
    "sslkey", "sslrootcert", "sslcrl", "sslcrldir", "connect_timeout",
    "application_name", "fallback_application_name", "client_encoding",
    "options", "keepalives", "keepalives_idle", "keepalives_interval",
    "keepalives_count", "target_session_attrs", "channel_binding",
    "replication", "gssencmode", "krbsrvname", "gsslib", "service",
    "requiressl", "sslcompression",
}


def sanitize_db_url(url: str) -> str:
    parsed = urllib.parse.urlsplit(url)
    if not parsed.query:
        return url
    keep = [kv for kv in parsed.query.split("&") if kv and kv.split("=")[0] in LIBPQ_PARAMS]
    return urllib.parse.urlunsplit(
        (parsed.scheme, parsed.netloc, parsed.path, "&".join(keep), parsed.fragment)
    )


class Database:
    def __init__(self, url: str):
        import psycopg2

        self.conn = psycopg2.connect(sanitize_db_url(url), connect_timeout=30)
        self.conn.autocommit = True
        self.cur = self.conn.cursor()

    def close(self) -> None:
        self.cur.close()
        self.conn.close()

    def fetch_eligible(self, cfg: Config) -> list[tuple]:
        statuses = ["pending"]
        include_failed = False
        if cfg.redo:
            statuses = ["pending", "completed", "failed"]
        elif cfg.retry_failed:
            statuses.append("failed")
            include_failed = True
        ph = ",".join(["%s"] * len(statuses))
        params: list = list(statuses)
        retry_clause = ""
        if include_failed:
            retry_clause = ' AND "transcriptionRetryCount" < %s'
            params.append(cfg.max_retries)
        self.cur.execute(
            f"""
            SELECT v.id, v.title, v."channelName", v."publishedAt"
            FROM "Video" v
            LEFT JOIN "Channel" c ON c.id = v."channelId"
            WHERE v.type = 'VIDEO'
              AND v."transcriptionStatus" IN ({ph})
              {retry_clause}
              AND (c.language IS NULL OR c.language = '' OR LOWER(c.language) = 'en')
            ORDER BY v."publishedAt" DESC
            LIMIT %s
            """,
            params + [cfg.batch_limit],
        )
        return self.cur.fetchall()

    def fetch_one(self, video_id: str) -> tuple | None:
        self.cur.execute(
            """SELECT id, title, "channelName", "publishedAt"
               FROM "Video" WHERE id=%s""",
            (video_id,),
        )
        return self.cur.fetchone()

    def fetch_content(self, video_id: str) -> tuple | None:
        self.cur.execute(
            """SELECT "content" FROM "Video" WHERE id=%s""",
            (video_id,),
        )
        return self.cur.fetchone()

    def mark_processing(self, video_id: str) -> None:
        self.cur.execute(
            """UPDATE "Video" SET "transcriptionStatus"='processing',
               "transcriptionProgress"=5, "lastTranscriptionError"=NULL
               WHERE "id"=%s""",
            (video_id,),
        )

    def release_stale_processing(self) -> None:
        self.cur.execute(
            """UPDATE "Video" SET "transcriptionStatus"='pending'
               WHERE "transcriptionStatus"='processing'"""
        )
        if self.cur.rowcount:
            log.info("  swept %d stale 'processing' row(s) back to 'pending'", self.cur.rowcount)

    def mark_progress(self, video_id: str, progress: int) -> None:
        self.cur.execute(
            """UPDATE "Video" SET "transcriptionProgress"=%s WHERE "id"=%s""",
            (progress, video_id),
        )

    def mark_completed(self, video_id: str, content: str) -> None:
        self.cur.execute(
            """UPDATE "Video" SET "transcriptionStatus"='completed',
               "content"=%s, "transcriptionProgress"=100, "lastTranscriptionError"=NULL
               WHERE "id"=%s""",
            (content, video_id),
        )

    def mark_failed(self, video_id: str, error: str) -> None:
        self.cur.execute(
            """UPDATE "Video" SET "transcriptionStatus"='failed',
               "lastTranscriptionError"=%s, "transcriptionRetryCount"="transcriptionRetryCount"+1
               WHERE "id"=%s""",
            (error[:2000], video_id),
        )


# --------------------------------------------------------------------------- #
# Audio download
# --------------------------------------------------------------------------- #
def download_audio(video_id: str, out_dir: Path) -> Path:
    url = f"https://www.youtube.com/watch?v={video_id}"
    log.info("  downloading audio: %s", url)
    cmd = [
        "yt-dlp",
        "--no-playlist",
        "--extract-audio",
        "--audio-format",
        "wav",
        "--audio-quality",
        "0",
        "--postprocessor-args",
        "-ar 16000 -ac 1",
        "-o",
        str(out_dir / f"{video_id}.%(ext)s"),
        url,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"yt-dlp failed: {result.stderr.strip()[-500:]}")
    wav = out_dir / f"{video_id}.wav"
    if not wav.exists():
        matches = list(out_dir.glob(f"{video_id}.wav"))
        if not matches:
            raise RuntimeError("yt-dlp completed but no wav produced")
        wav = matches[0]
    return wav


def load_wav_to_float32(path: Path) -> np.ndarray:
    import numpy as np  # noqa: E402

    with wave.open(str(path), "rb") as w:
        assert w.getnchannels() == 1, "expected mono audio"
        assert w.getsampwidth() == 2, "expected 16-bit audio"
        data = w.readframes(w.getnframes())
    return np.frombuffer(data, dtype=np.int16).astype(np.float32) / 32768.0


def fmt_ts(seconds: float) -> str:
    m, s = divmod(int(round(seconds)), 60)
    h, m = divmod(m, 60)
    return f"{h:02d}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"


# --------------------------------------------------------------------------- #
# GitHub releases repo (Contents API only — no local git credentials)
# --------------------------------------------------------------------------- #
class GitHubRepo:
    def __init__(self, repo: str, token: str):
        import requests  # noqa: E402

        self._requests = requests
        self.api = "https://api.github.com"
        self.repo = repo
        self.headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    def _url(self, path: str) -> str:
        import urllib.parse  # noqa: E402

        return f"{self.api}/repos/{self.repo}/contents/{urllib.parse.quote(path)}"

    def upsert(self, path: str, content: str, message: str) -> str:
        body: dict = {"message": message, "content": base64.b64encode(content.encode("utf-8")).decode("ascii")}
        existing = self._requests.get(self._url(path), headers=self.headers, timeout=30)
        if existing.status_code == 200:
            body["sha"] = existing.json()["sha"]
        elif existing.status_code != 404:
            raise RuntimeError(f"GitHub GET {path} -> {existing.status_code}: {existing.text[:300]}")
        resp = self._requests.put(self._url(path), json=body, headers=self.headers, timeout=30)
        if resp.status_code not in (200, 201):
            raise RuntimeError(f"GitHub PUT {path} -> {resp.status_code}: {resp.text[:300]}")
        return resp.json().get("content", {}).get("html_url", f"contents/{path}")

    def get_or(self, path: str, default: object) -> object:
        resp = self._requests.get(self._url(path), headers=self.headers, timeout=30)
        if resp.status_code == 404:
            return default
        if resp.status_code != 200:
            raise RuntimeError(f"GitHub GET {path} -> {resp.status_code}: {resp.text[:300]}")
        return resp.json()

    def read_text_or_none(self, path: str) -> str | None:
        import json  # noqa: E402

        data = self.get_or(path, None)
        if data is None:
            return None
        return base64.b64decode(data["content"]).decode("utf-8")


# --------------------------------------------------------------------------- #
# Local LLM (Ollama)
# --------------------------------------------------------------------------- #
class LLM:
    def __init__(self, url: str, model: str, context: int, timeout: int = 1800):
        import requests  # noqa: E402

        self._requests = requests
        self.url = url
        self.model = model
        self.context = context
        self.timeout = timeout

    def ensure_model(self) -> None:
        tags = self._requests.get(f"{self.url}/api/tags", timeout=15)
        tags.raise_for_status()
        have = {m.get("name") for m in tags.json().get("models", [])}
        if self.model in have:
            return
        log.info("  pulling LLM model %s (first run only)...", self.model)
        pull = self._requests.post(
            f"{self.url}/api/pull",
            json={"name": self.model},
            stream=True,
            timeout=None,
        )
        pull.raise_for_status()
        # drain the NDJSON progress stream
        for _ in pull.iter_lines():
            pass
        log.info("  LLM model %s ready.", self.model)

    def generate_json(self, system: str, user: str) -> dict:
        import json  # noqa: E402
        import time  # noqa: E402

        payload = {
            "model": self.model,
            "stream": False,
            "keep_alive": "30m",
            "format": "json",
            "options": {"num_ctx": self.context, "temperature": 0.1},
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        }
        url = f"{self.url}/api/chat"
        last_err: Exception | None = None
        for attempt in range(1, 4):
            try:
                resp = self._requests.post(url, json=payload, timeout=self.timeout)
                resp.raise_for_status()
                raw = resp.json().get("message", {}).get("content", "")
                return json.loads(raw)
            except (
                self._requests.exceptions.Timeout,
                self._requests.exceptions.ConnectionError,
                self._requests.exceptions.HTTPError,
            ) as e:
                last_err = e
                log.warning("  LLM call attempt %d/3 failed: %s", attempt, e)
                if attempt < 3:
                    time.sleep(30 * attempt)
        raise last_err or RuntimeError("LLM call failed after retries")


# --------------------------------------------------------------------------- #
# Transcription
#
# Two interchangeable backends, both exposing `transcribe(wav_path, language)`
# returning the `[MM:SS -> MM:SS] ...` transcript string:
#   - WhisperClient  HTTP POST to a native whisper server (Windows host).
#   - Transcriber    in-process faster-whisper (Docker fallback).
# Chosen by Config.whisper_url: set => WhisperClient, else in-process.
# --------------------------------------------------------------------------- #
class Transcriber:
    def __init__(self, cfg: Config):
        from faster_whisper import WhisperModel  # noqa: E402

        self.model = WhisperModel(
            cfg.whisper_model,
            device=cfg.whisper_device,
            compute_type=cfg.whisper_compute,
            download_root=str(cfg.whisper_model_dir),
        )
        log.info("Loaded Whisper '%s' (%s/%s) from %s",
                 cfg.whisper_model, cfg.whisper_device, cfg.whisper_compute, cfg.whisper_model_dir)

    def transcribe(self, wav_path: Path, language: str | None = "en") -> str:
        audio = load_wav_to_float32(wav_path)
        segments, _info = self.model.transcribe(
            audio,
            language=language,
            vad_filter=True,
            beam_size=5,
            condition_on_previous_text=True,
            temperature=[0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
        )
        return "\n".join(
            f"[{fmt_ts(s.start)} -> {fmt_ts(s.end)}] {s.text.strip()}" for s in segments
        )


class WhisperClient:
    def __init__(self, url: str, timeout: int = 3600):
        import requests  # noqa: E402

        self._requests = requests
        self.url = url.rstrip("/")
        self.timeout = timeout

    def transcribe(self, wav_path: Path, language: str | None = "en") -> str:
        with open(wav_path, "rb") as f:
            resp = self._requests.post(
                f"{self.url}/transcribe",
                files={"file": (wav_path.name, f, "audio/wav")},
                data={"language": language or ""},
                timeout=self.timeout,
            )
        resp.raise_for_status()
        segs = resp.json().get("segments", []) or []
        if not segs:
            return ""
        return "\n".join(
            f"[{fmt_ts(float(s['start']))} -> {fmt_ts(float(s['end']))}] "
            f"{(s.get('text') or '').strip()}" for s in segs
        )


def build_transcriber(cfg: Config):
    if cfg.whisper_url:
        log.info("Using HTTP whisper server at %s", cfg.whisper_url)
        return WhisperClient(cfg.whisper_url)
    log.info("Using in-process faster-whisper")
    return Transcriber(cfg)


# --------------------------------------------------------------------------- #
# Insight extraction prompt
# --------------------------------------------------------------------------- #
SYSTEM_PROMPT = """You are a meticulous Bible scholar analysing a sermon transcript.
Extract, without inventing anything that is not actually in the transcript:

1. "bibleQuotes": every Scripture verse the preacher quoted or clearly paraphrased.
   Fields: "quote" (the exact words as spoken, keep short), "reference" (best-guess
   book chapter:verse, e.g. "Romans 3:23"), "confidence" (high|medium|low), and
   "context" (one short sentence about where it appears).
2. "ideas": key theological/doctrinal points the preacher made.
3. "truths": standalone spiritual principles or life applications taught.
4. "themes": 3-8 broad themes of the sermon.
5. "keywords": up to 10 single terms for search.
6. "summary": a 4-6 sentence summary of the whole transcript.

Rules:
- Only quote Scripture that actually appears (or is explicitly cited) in the text.
- Never fabricate references; if unsure, still give a best-guess reference but mark
  confidence "low".
- Respond ONLY with valid JSON matching this exact shape:
{"bibleQuotes":[{"quote":"...","reference":"...","confidence":"high|medium|low","context":"..."}],"ideas":["..."],"truths":["..."],"themes":["..."],"keywords":["..."],"summary":"..."}"""


# --------------------------------------------------------------------------- #
# Pipeline helpers
# --------------------------------------------------------------------------- #
def _estimate_tokens(text: str) -> int:
    return int(len(text) / 3.7)  # rough English token estimate


def _chunk_transcript(text: str, budget_chars: int) -> list[str]:
    if len(text) <= budget_chars:
        return [text]
    lines = text.split("\n")
    chunks: list[str] = []
    cur: list[str] = []
    cur_len = 0
    for line in lines:
        if cur_len + len(line) + 1 > budget_chars and cur:
            chunks.append("\n".join(cur))
            cur, cur_len = [], 0
        cur.append(line)
        cur_len += len(line) + 1
    if cur:
        chunks.append("\n".join(cur))
    return chunks


def _dedupe(items: list, key) -> list:
    seen: set = set()
    out = []
    for it in items:
        k = key(it)
        if k in seen:
            continue
        seen.add(k)
        out.append(it)
    return out


def extract_insights(llm: LLM, transcript: str) -> dict:
    reserve = 4000
    avail = llm.context - reserve
    budget_chars = min(max(4000, int(avail * 3.7)), 25000)
    chunks = _chunk_transcript(transcript, budget_chars)
    parts = []
    total = len(chunks)
    for i, chunk in enumerate(chunks, start=1):
        meta = "" if total == 1 else (
            f"\n\n[NOTE: this is part {i} of {total}; extract everything you find in this part.]"
        )
        parts.append(
            llm.generate_json(
                SYSTEM_PROMPT,
                f"TRANSCRIPT:\n{chunk}{meta}\n\nReturn the JSON now.",
            )
        )
        log.info("  extracted part %d/%d", i, total)

    if len(parts) == 1:
        return parts[0]

    quotes = [q for p in parts for q in p.get("bibleQuotes", [])]
    quotes = _dedupe(quotes, lambda q: (q.get("reference", ""), q.get("quote", "").lower()))
    return {
        "bibleQuotes": quotes,
        "ideas": _dedupe([i for p in parts for i in p.get("ideas", [])], str.lower),
        "truths": _dedupe([t for p in parts for t in p.get("truths", [])], str.lower),
        "themes": _dedupe([t for p in parts for t in p.get("themes", [])], str.lower),
        "keywords": _dedupe([k for p in parts for k in p.get("keywords", [])], str.lower),
        "summary": " ".join(p.get("summary", "") for p in parts if p.get("summary")),
    }


def _build_manifest(repo: GitHubRepo) -> list[dict]:
    raw = repo.read_text_or_none("index.json")
    if raw is None:
        return []
    import json  # noqa: E402

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        log.warning("  index.json in repo was invalid JSON; starting fresh.")
        return []
    return data if isinstance(data, list) else []


def update_manifest(repo: GitHubRepo, entry: dict) -> None:
    entries = [e for e in _build_manifest(repo) if e.get("videoId") != entry["videoId"]]
    entries.append(entry)
    entries.sort(key=lambda e: e.get("publishedAt", ""), reverse=True)
    import json  # noqa: E402

    repo.upsert("index.json", json.dumps(entries, indent=2, ensure_ascii=False), f"manifest: {entry['videoId']}")


def _interrupted() -> bool:
    return _split_to_epoch is not None and time.time() >= _split_to_epoch


# --------------------------------------------------------------------------- #
# Per-video processing
# --------------------------------------------------------------------------- #
def process_video(db: Database, cfg: Config, trans: Transcriber, llm: LLM,
                  repo: GitHubRepo, row: tuple) -> None:
    video_id, title, channel, published_at = row
    mark = f"-> {video_id} | {title} ({channel})"
    log.info(">> Processing %s", mark)
    try:
        db.mark_processing(video_id)
        transcript: str | None = None
        if cfg.insights_resume:
            got = db.fetch_content(video_id)
            if got and got[0]:
                transcript = got[0]
                log.info("  resuming: reusing existing transcript from DB (%d chars)", len(transcript))
        if transcript is None:
            with tempfile.TemporaryDirectory(prefix="tw_", dir=str(cfg.work_dir)) as tmp:
                wav = download_audio(video_id, Path(tmp))
                db.mark_progress(video_id, 40)
                transcript = trans.transcribe(wav)
                db.mark_progress(video_id, 70)
                log.info("  transcript: %d chars", len(transcript))

            db.mark_completed(video_id, transcript)
            log.info("  saved transcript to DB (status=completed)")

            # 1) Transcript -> transcripts/<id>.md
            md = f"# {title}\n\n- Video: https://www.youtube.com/watch?v={video_id}\n- Channel: {channel}\n\n---\n\n{transcript}\n"
            url = repo.upsert(
                f"transcripts/{video_id}.md",
                md,
                f"Add transcript {video_id}",
            )
            log.info("  pushed transcript: %s", url)
        else:
            log.info("  transcript already published; skipping re-push")
            # Insights-only resume: restore the row to 'completed' (idempotent —
            # content is unchanged, so mark_completed just clears the
            # manual 'processing' flag now that the run succeeded).
            db.mark_completed(video_id, transcript)

        # 2) Insights via local LLM -> insights/<id>.json
        db.mark_progress(video_id, 80)
        if llm is not None:
            payload = extract_insights(llm, transcript)
            import json  # noqa: E402

            doc = {
                "videoId": video_id,
                "title": title,
                "channel": channel,
                "publishedAt": published_at.isoformat() if hasattr(published_at, "isoformat") else str(published_at),
                "llm": {"model": cfg.llm_model, "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())},
                "insights": payload,
            }
            url = repo.upsert(
                f"insights/{video_id}.json",
                json.dumps(doc, indent=2, ensure_ascii=False),
                f"Add insights {video_id}",
            )
            log.info("  pushed insights: %s", url)

        # 3) Manifest
        update_manifest(repo, {
            "videoId": video_id,
            "title": title,
            "channel": channel,
            "publishedAt": getattr(published_at, "isoformat", lambda: str(published_at))(),
            "transcript": f"transcripts/{video_id}.md",
            "insights": f"insights/{video_id}.json",
            "updatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        })
        db.mark_progress(video_id, 100)
        log.info(">> Done: %s", video_id)
    except Exception as e:  # noqa: BLE001
        log.error(">> Failed %s: %s", video_id, e)
        db.mark_failed(video_id, str(e))


# --------------------------------------------------------------------------- #
# Main loop
# --------------------------------------------------------------------------- #
def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Transcribe pending videos and publish transcripts + AI insights to GitHub.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--once", action="store_true", help="Process a single batch, then exit (no poll loop).")
    p.add_argument("--retry-failed", action="store_true", help="Also include 'failed' videos (under retry cap).")
    p.add_argument("--redo", action="store_true", help="Re-transcribe / re-publish already completed videos.")
    p.add_argument("--video-id", help="Process a single specific video by YouTube ID.")
    p.add_argument("--no-llm", action="store_true", help="Skip LLM insight extraction (transcript + manifest only).")
    p.add_argument("--insights-resume", action="store_true",
                   help="With --video-id: reuse the stored transcript and run LLM insights only "
                        "(no re-download / re-transcription / transcript re-push).")
    return p.parse_args(argv)


def run(ctx: Config, rows: list[tuple]) -> int:
    db = Database(ctx.database_url)
    trans = build_transcriber(ctx)
    llm: LLM | None = None
    if ctx.no_llm:
        log.warning("  LLM stage skipped (--no-llm).")
    else:
        llm = LLM(ctx.llm_url, ctx.llm_model, ctx.llm_context, ctx.llm_timeout)
        # Ensure the model is present before churning through the backlog.
        llm.ensure_model()
    repo = GitHubRepo(ctx.github_repo, ctx.github_token)

    try:
        first = True
        while True:
            if _interrupted():
                log.info("Shutdown requested; exiting cleanly.")
                return 0
            if first:
                batch = rows
            else:
                batch = db.fetch_eligible(ctx)
            if not batch:
                log.info("Backlog empty; sleeping %ds before re-check...", ctx.poll_interval)
            else:
                log.info("Selected %d video(s):", len(batch))
                for vid, title, ch, _pub in batch:
                    log.info("  - %s | %s (%s)", vid, title, ch)
                for row_tuple in batch:
                    if _interrupted():
                        return 0
                    process_video(db, ctx, trans, llm, repo, row_tuple)
            first = False
            if ctx.once:
                return 0 if batch else 2
            deadline = time.time() + ctx.poll_interval
            while not _interrupted() and time.time() < deadline:
                time.sleep(5)
    finally:
        db.close()


def main(argv: list[str] | None = None) -> int:
    global _split_to_epoch
    args = parse_args(argv or sys.argv[1:])

    def _handle(signum, _frame):
        global _split_to_epoch
        log.info("Signal %s received; finishing current video then exiting.", signum)
        _split_to_epoch = time.time() + 30

    signal.signal(signal.SIGTERM, _handle)
    signal.signal(signal.SIGINT, _handle)

    ctx = load_config(args)
    if ctx.video_id:
        ctx.once = True
    ctx.work_dir.mkdir(parents=True, exist_ok=True)
    ctx.whisper_model_dir.mkdir(parents=True, exist_ok=True)

    db = Database(ctx.database_url)
    db.release_stale_processing()
    try:
        if ctx.video_id:
            row = db.fetch_one(ctx.video_id)
            rows = [row] if row else []
            if not rows:
                log.error("Video %s not found in database.", ctx.video_id)
                return 1
        else:
            rows = db.fetch_eligible(ctx)
    finally:
        db.close()

    return run(ctx, rows)


if __name__ == "__main__":
    sys.exit(main())