param (
    [string]$InstanceId = "christian_tube"
)

$RootDir = Split-Path -Parent $PSScriptRoot
$InstanceDir = Join-Path $RootDir "instances\$InstanceId"

if (-not (Test-Path $InstanceDir)) {
    Write-Error "Error: Instance directory '$InstanceDir' does not exist!"
    exit 1
}

$ConfigFile = Join-Path $InstanceDir "config.json"
if (-not (Test-Path $ConfigFile)) {
    Write-Error "Error: Config file '$ConfigFile' not found!"
    exit 1
}

$Config = Get-Content $ConfigFile -Raw | ConvertFrom-Json
Write-Host "🚀 Preparing PrivateTube engine for instance: $($Config.appName) ($InstanceId)..."

# 1. Copy config to mobile assets
$MobileAssets = Join-Path $RootDir "apps\mobile\assets"
New-Item -ItemType Directory -Path $MobileAssets -Force | Out-Null
Copy-Item -Path $ConfigFile -Destination (Join-Path $MobileAssets "app_config.json") -Force
Write-Host "✅ Synced app_config.json to mobile assets"

# 2. Copy icon
$IconSrc = Join-Path $InstanceDir "assets\icon.png"
if (Test-Path $IconSrc) {
    Copy-Item -Path $IconSrc -Destination (Join-Path $MobileAssets "logo.png") -Force
    Write-Host "✅ Synced logo.png to mobile assets"

    # Mipmap icons
    $ResDir = Join-Path $RootDir "apps\mobile\android\app\src\main\res"
    try {
        $PythonCode = "import os, sys; from PIL import Image; src = sys.argv[1]; res = sys.argv[2]; img = Image.open(src).convert('RGBA'); sizes = {'mipmap-mdpi': 48, 'mipmap-hdpi': 72, 'mipmap-xhdpi': 96, 'mipmap-xxhdpi': 144, 'mipmap-xxxhdpi': 192}; [os.makedirs(os.path.join(res, f), exist_ok=True) or (lambda s: (lambda c, r, x, y: (c.paste(r, (x, y), r), c.save(os.path.join(res, f, 'ic_launcher.png'), 'PNG')))(Image.new('RGBA', (s, s), (0,0,0,0)), img.resize((max(1, int(img.width * min(s*0.84/img.width, s*0.84/img.height))), max(1, int(img.height * min(s*0.84/img.width, s*0.84/img.height)))), Image.Resampling.LANCZOS), (s - max(1, int(img.width * min(s*0.84/img.width, s*0.84/img.height))))//2, (s - max(1, int(img.height * min(s*0.84/img.width, s*0.84/img.height))))//2))(sz) for f, sz in sizes.items()]"
        python -c "$PythonCode" "$IconSrc" "$ResDir"
        Write-Host "✅ Generated resized Android launcher icons (48x48 to 192x192)"
    } catch {
        @('mipmap-mdpi', 'mipmap-hdpi', 'mipmap-xhdpi', 'mipmap-xxhdpi', 'mipmap-xxxhdpi') | ForEach-Object {
            $TargetDir = Join-Path $ResDir $_
            New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
            Copy-Item -Path $IconSrc -Destination (Join-Path $TargetDir "ic_launcher.png") -Force
        }
        Write-Host "✅ Synced Android launcher icons across all mipmap densities"
    }
}

# 3. Update build.gradle applicationId
$BuildGradlePath = Join-Path $RootDir "apps\mobile\android\app\build.gradle"
if (Test-Path $BuildGradlePath) {
    $GradleContent = Get-Content $BuildGradlePath -Raw
    $GradleContent = $GradleContent -replace 'applicationId\s*=\s*"[^"]*"', "applicationId = `"$($Config.applicationId)`""
    Set-Content -Path $BuildGradlePath -Value $GradleContent -NoNewline
    Write-Host "✅ Updated Android applicationId to: $($Config.applicationId)"
}

# 4. Update AndroidManifest.xml
$ManifestPath = Join-Path $RootDir "apps\mobile\android\app\src\main\AndroidManifest.xml"
if (Test-Path $ManifestPath) {
    $ManifestContent = Get-Content $ManifestPath -Raw
    $ManifestContent = $ManifestContent -replace 'android:label="[^"]*"', "android:label=`"$($Config.appName)`""
    Set-Content -Path $ManifestPath -Value $ManifestContent -NoNewline
    Write-Host "✅ Updated AndroidManifest label to: $($Config.appName)"
}

# 5. Generate active_engine.g.dart for compile-time tree-shaking
$EngineBridgePath = Join-Path $RootDir "apps\mobile\lib\core\engines\active_engine.g.dart"
$MicroFeed = $Config.microFeed
$EngineType = if ($MicroFeed) { $MicroFeed.engine } else { $null }

if (-not $MicroFeed -or -not $MicroFeed.enabled -or -not $EngineType) {
    $BridgeContent = @"
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by prepare-instance.ps1 for instance: $($Config.instanceId) (DISABLED)

import 'base_feed_engine.dart';

const bool kMicroFeedEnabled = false;

BaseFeedEngine? createActiveFeedEngine() => null;
"@
} elseif ($EngineType -eq "scripture") {
    $BridgeContent = @"
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by prepare-instance.ps1 for instance: $($Config.instanceId)

import 'base_feed_engine.dart';
import '../../features/engines/scripture/scripture_engine.dart';

const bool kMicroFeedEnabled = true;

BaseFeedEngine? createActiveFeedEngine() => ScriptureEngine();
"@
} else {
    $BridgeContent = @"
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by prepare-instance.ps1 for instance: $($Config.instanceId) ($EngineType)

import 'base_feed_engine.dart';

const bool kMicroFeedEnabled = false;

BaseFeedEngine? createActiveFeedEngine() => null;
"@
}

Set-Content -Path $EngineBridgePath -Value $BridgeContent -NoNewline
Write-Host "✅ Generated active_engine.g.dart for [$(if ($MicroFeed -and $MicroFeed.enabled) { $EngineType } else { 'DISABLED' })]"

Write-Host "🎉 Instance preparation complete for $($Config.appName)!"
